library(nnet)
kapselstat=read.csv("datasample.csv")
head(kapselstat)
y=kapselstat[,4]
y=factor(y)
levels(y)=c("Uber,dll","Grab","Gojek")
y=relevel(y,ref="Uber,dll")
x1=kapselstat[,1]
x1=factor(x1)
levels(x1)=c("Luar Jawa","Jawa")
x2=kapselstat[,2]
x2=factor(x2)
levels(x2)=c("Bekerja","Pelajar/Mahasiswa")
x3=kapselstat[,3]
x3=factor(x3)
levels(x3)=c("Pelayanan terjamin","Aplikasi mudah","Harga")
kapselstat[,1]=x1
kapselstat[,2]=x2
kapselstat[,3]=x3
kapselstat[,4]=y
kapselstat
test<-multinom(y~x1+x2+x3,data=kapselstat)
summary(test)
z<-summary(test)$coefficients/summary(test)$standard.errors
z
p<-(1-pnorm(abs(z),0,1))*2
p
OR=exp(coef(test))
OR
prediksi<-predict(test,data=kapselstat,type="prob")
prediksi<-predict(test,data=kapselstat)
aktual=y
table(aktual,prediksi)
library(lmtest)
testx1<-multinom(y~x2+x3,data=kapselstat)
lrtest(test,testx1)
testx2<-multinom(y~x1+x3,data=kapselstat)
lrtest(test,testx2)
testx3<-multinom(y~x1+x2,data=kapselstat)
lrtest(test,testx3)
library(DescTools)
PseudoR2(test,which=c("CoxSnell","Nagelkerke","McFadden"))
chisq.test(y,predict(test))
